# Change baseurl before deploy
baseurl = "https://blog.cloudorz.com"
languageCode = "zh-cn"
title = "Tuan's Blog"
copyright = "mt"

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

[pagination]
pagerSize = 8

